
name: Demo resource groups

#env:
#  AZURE_WEBAPP_NAME: your-app-name  # set this to the name of your Azure Web App

on:
  workflow_dispatch:

jobs:

  list-groups:
    runs-on: ubuntu-latest
    steps:
    - name: Azure login
    #  uses: azure/login@v1.4.3
    #  with:
    #    client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: which az
    - run: az --version
    
    - run: |
        az group list --query "[?name.contains(@, 'demo')]" | jq '.[] | .name'
