
name: Demo resource groups

#env:
#  AZURE_WEBAPP_NAME: your-app-name  # set this to the name of your Azure Web App

on:
  workflow_dispatch:

jobs:

  list-groups:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Get demo resource groups
      run: |
        az group list --query "[?name.contains(@, 'demo')]" | jq -r '.[] | .name' > demo-groups.txt

    - name: Remove demo resource groups    
      run: |
        while read -r group; do
            az group show -n $group;
        done < demo-groups.txt
