
name: Nuke Demo resource groups

on:
  workflow_dispatch:

jobs:

  rm-resource-groups:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Get demo resource groups
      run: |
        az group list --query "[?name.contains(@, 'demo')]" | jq -r '.[] | .name' > demo-groups.txt

    - name: Remove demo resource groups    
      run: |
        while read -r group; do
            az group delete -yn $group;
        done < demo-groups.txt
